# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20160818_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_up_at',
            field=models.DateTimeField(null=True),
        ),
    ]
