# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-16 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('c', 'Create'), ('u', 'Update'), ('d', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('identity_id', models.UUIDField()),
                ('subscription_id', models.UUIDField(null=True)),
                ('detail', models.TextField(null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_action_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
